package ui

import (
	"fmt"
)

// PrintMainMenu imprime el menú principal (igual al script original)
func MainMenu() {
	fmt.Println()
	fmt.Println("                                #    ######  ######        ###   ######  ####### ######  #######")
	fmt.Println("                               # #   #     # #     #        #    #     # #       #     # #")
	fmt.Println("                              #   #  #     # #     #        #    #     # #       #     # #")
	fmt.Println("                             #     # ######  ######         #    ######  #####   ######  #####")
	fmt.Println("                             ####### #       #              #    #       #       #   #   #")
	fmt.Println("                             #     # #       #              #    #       #       #    #  #")
	fmt.Println("                             #     # #       #             ###   #       ####### #     # #")
	fmt.Println("                             ")
	fmt.Println("                                                   Telefonica Chile")
	fmt.Println()
	fmt.Println()
	fmt.Println("     MENU PRINCIPAL")
	fmt.Println()
	fmt.Println("     Seleccionar una opcion:")
	fmt.Println()
	fmt.Println("     1) - Autoaprovisionamiento (ZTP) de NIC cableada")
	fmt.Println()
	fmt.Println("     2) - Prueba Iperf Internet")
	fmt.Println()
	fmt.Println("     3) - Prueba Iperf MPLS")
	fmt.Println()
	fmt.Println("     4) - Prueba Iperf Punto a Punto")
	fmt.Println()
	fmt.Println("     5) - Diagnostico de conectividad (ping,tracert,etc)")
	fmt.Println()
	fmt.Println("     6) - Carpeta Iperf")
	fmt.Println()
	fmt.Println("     7) - Salir")
	fmt.Println()
}

func IperfP2PMenu() {
	fmt.Println("                 ###   ######  ####### ######  #######     ######   #####  ###### ")
	fmt.Println("                  #    #     # #       #     # #           #     # #     # #     #")
	fmt.Println("                  #    #     # #       #     # #           #     #       # #     #")
	fmt.Println("                  #    ######  #####   ######  #####       ######   #####  ###### ")
	fmt.Println("                  #    #       #       #   #   #           #       #       #      ")
	fmt.Println("                  #    #       #       #    #  #           #       #       #      ")
	fmt.Println("                 ###   #       ####### #     # #           #       ####### #      ")
	fmt.Println()
	fmt.Println()
	fmt.Println("     MENU IPERF PUNTO A PUNTO")
	fmt.Println()
	fmt.Println("     Seleccionar una opcion:")
	fmt.Println()
	fmt.Println()
	fmt.Println("     1) - Prueba Iperf en Modo Cliente")
	fmt.Println()
	fmt.Println("     2) - Prueba Iperf en Modo Servidor")
	fmt.Println()
	fmt.Println("     3) - Volver al menu principal")
	fmt.Println()
}

func IperfInternetMenu() {
	fmt.Println("                      ###   ######  ####### ######  #######     ###   #     # ####### #######")
	fmt.Println("                       #    #     # #       #     # #            #    ##    # #          #")
	fmt.Println("                       #    #     # #       #     # #            #    # #   # #          #")
	fmt.Println("                       #    ######  #####   ######  #####        #    #  #  # #####      #")
	fmt.Println("                       #    #       #       #   #   #            #    #   # # #          #")
	fmt.Println("                       #    #       #       #    #  #            #    #    ## #          #")
	fmt.Println("                      ###   #       ####### #     # #           ###   #     # #######    #")
	fmt.Println()
	fmt.Println()
	fmt.Println("     MENU IPERF INTERNET")
	fmt.Println()
	fmt.Println("     Seleccionar una opcion:")
	fmt.Println()
	fmt.Println()
	fmt.Println("     1) - Prueba Iperf Internet Nacional (181.212.30.100)")
	fmt.Println()
	fmt.Println("     2) - Prueba Iperf Internet Internacional (iperf.volia.net)")
	fmt.Println()
	fmt.Println("     3) - Volver al menu principal")
	fmt.Println()
}

func DiagnosticMenu() {
	fmt.Println("     MENU DE DIAGNOSTICO DE CONECTIVIDAD")
	fmt.Println()
	fmt.Println("     Seleccionar una opcion:")
	fmt.Println()
	fmt.Println()
	fmt.Println("     1) - Ping al servidor Iperf")
	fmt.Println()
	fmt.Println("     2) - Traza al servidor Iperf")
	fmt.Println()
	fmt.Println("     3) - Tabla de enrutamiento notebook")
	fmt.Println()
	fmt.Println("     4) - Forzar ruta estatica hacia servidor iperf - MPLS")
	fmt.Println()
	fmt.Println("     5) - Forzar ruta estatica hacia servidor iperf - P2P")
	fmt.Println()
	fmt.Println("     6) - Volver al menu principal")
	fmt.Println()
}
